name: Deploy Test Lambda For Clien

on:
  push:
    branches:
      - extract/clien  # develop 브랜치에 push될 때 실행

jobs:
  deploy-test-lambda:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # GitHub OIDC 사용을 위한 설정
      contents: read

    steps:
      - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-2

    - name: Build & Push Test Lambda Image
      run: |
        TARGET_DIR="extract/clien"  # 특정 디렉토리 설정
        LAMBDA_NAME=$(basename $TARGET_DIR)
        TEST_LAMBDA_NAME="test-extract-$LAMBDA_NAME"
        IMAGE_URI="${{ secrets.AWS_ECR_REGISTRY }}/vroomcast/$TEST_LAMBDA_NAME:latest"

        echo "Building & Deploying Test Lambda: $TEST_LAMBDA_NAME"
        docker build -t vroomcast/$TEST_LAMBDA_NAME $TARGET_DIR
        docker tag vroomcast/$TEST_LAMBDA_NAME:latest $IMAGE_URI
        docker push $IMAGE_URI

        echo "Creating or Updating Test Lambda: $TEST_LAMBDA_NAME"
        aws lambda create-function \
          --function-name $TEST_LAMBDA_NAME \
          --package-type Image \
          --code ImageUri=$IMAGE_URI \
          --role ${{ secrets.AWS_LAMBDA_EXECUTION_ROLE }} \
          --region ap-northeast-2 || \
        aws lambda update-function-code \
          --function-name $TEST_LAMBDA_NAME \
          --image-uri $IMAGE_URI \
          --region ap-northeast-2

    - name: Invoke Test Lambda
      run: |
        echo "Invoking Test Lambda: $TEST_LAMBDA_NAME"
        aws lambda invoke --function-name $TEST_LAMBDA_NAME \
          --payload '{ "car_id": "test-github", "keywords": ["캐스퍼"], "date": "2025-02-10", "bucket": "hmg-5th-crawling-test"}' \
          response.json \
          --region ap-northeast-2 
        cat response.json
